import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-navy text-white flex`}
      >
         <div className="flex">
           {/* Sidebar */}
           <div className="hidden md:block">
             {/* @ts-ignore */}
             {require('../components/layout/Sidebar').default()}
           </div>
           <div className="flex-1 flex flex-col min-h-screen">
             {/* Topbar */}
             {/* @ts-ignore */}
             {require('../components/layout/Topbar').default()}
             <main className="flex-1 p-6">
               {children}
             </main>
           </div>
         </div>
      </body>
    </html>
  );
}
