package doc

func digitalTwinSchemas() M {
	return M{
		// ── Digital Twins ─────────────────────────────────────────────────────
		"DigitalTwinReconciliationPolicy": Props(nil, M{
			"strategy":        Str("source_priority | freshest"),
			"source_priority": Arr(M{"type": "string"}),
		}),
		"DigitalTwinConfig": Props(nil, M{
			"storage_ids":          Arr(M{"type": "string"}),
			"enable_predictions":   Bool("Whether prediction endpoints are enabled for this twin"),
			"prediction_cache_ttl": Int("Prediction cache TTL in seconds"),
			"reconciliation":       Ref("DigitalTwinReconciliationPolicy"),
			"custom_settings":      M{"type": "object", "additionalProperties": M{"type": "string"}},
		}),
		"DigitalTwin": Props(nil, M{
			"id":           Str("Digital twin ID (UUID)"),
			"project_id":   Str("Owning project ID"),
			"ontology_id":  Str("Linked ontology ID"),
			"name":         Str("Digital twin name"),
			"description":  Str("Description"),
			"status":       Str("active | syncing | error"),
			"config":       Ref("DigitalTwinConfig"),
			"metadata":     M{"type": "object", "additionalProperties": true},
			"created_at":   Str("ISO-8601 creation timestamp"),
			"updated_at":   Str("ISO-8601 last-updated timestamp"),
			"last_sync_at": Str("ISO-8601 timestamp of the most recent completed sync"),
		}),
		"DigitalTwinCreateRequest": Props([]string{"project_id", "ontology_id", "name"}, M{
			"project_id":  Str("Owning project ID"),
			"ontology_id": Str("Linked ontology ID"),
			"name":        Str("Digital twin name"),
			"description": Str("Description"),
			"config":      Ref("DigitalTwinConfig"),
		}),
		"DigitalTwinUpdateRequest": Props(nil, M{
			"name":        Str("New name"),
			"description": Str("New description"),
			"status":      Str("New status"),
			"config":      Ref("DigitalTwinConfig"),
		}),
		"Automation": Props(nil, M{
			"id":               Str("Automation ID (UUID)"),
			"project_id":       Str("Owning project ID"),
			"name":             Str("Automation name"),
			"description":      Str("Description"),
			"enabled":          Bool("Whether the automation is active"),
			"target_type":      Str("pipeline | digital_twin"),
			"target_id":        Str("Target resource ID"),
			"trigger_type":     Str("pipeline_completed | manual"),
			"trigger_config":   M{"type": "object", "additionalProperties": true},
			"condition_config": M{"type": "object", "additionalProperties": true},
			"action_type":      Str("process_twin | trigger_export_pipeline"),
			"action_config":    M{"type": "object", "additionalProperties": true},
			"created_at":       Str("ISO-8601 creation timestamp"),
			"updated_at":       Str("ISO-8601 last-updated timestamp"),
		}),
		"AutomationCreateRequest": Props([]string{"name"}, M{
			"name":             Str("Automation name"),
			"description":      Str("Description"),
			"enabled":          Bool("Whether the automation starts enabled"),
			"target_type":      Str("pipeline | digital_twin (overridden for twin-scoped routes)"),
			"target_id":        Str("Target resource ID (overridden for twin-scoped routes)"),
			"trigger_type":     Str("pipeline_completed | manual"),
			"trigger_config":   M{"type": "object", "additionalProperties": true},
			"condition_config": M{"type": "object", "additionalProperties": true},
			"action_type":      Str("process_twin | trigger_export_pipeline"),
			"action_config":    M{"type": "object", "additionalProperties": true},
		}),
		"AutomationUpdateRequest": Props(nil, M{
			"name":             Str("Automation name"),
			"description":      Str("Description"),
			"enabled":          Bool("Whether the automation is active"),
			"trigger_type":     Str("pipeline_completed | manual"),
			"trigger_config":   M{"type": "object", "additionalProperties": true},
			"condition_config": M{"type": "object", "additionalProperties": true},
			"action_type":      Str("process_twin | trigger_export_pipeline"),
			"action_config":    M{"type": "object", "additionalProperties": true},
		}),
		"TwinProcessingStageState": Props(nil, M{
			"status":       Str("queued | running | completed | failed | skipped"),
			"started_at":   Str("Stage start timestamp"),
			"completed_at": Str("Stage completion timestamp"),
			"metrics":      M{"type": "object", "additionalProperties": true},
			"error":        Str("Stage error, if any"),
		}),
		"TwinProcessingRun": Props(nil, M{
			"id":                   Str("Twin processing run ID (UUID)"),
			"project_id":           Str("Owning project ID"),
			"digital_twin_id":      Str("Owning digital twin ID"),
			"status":               Str("queued | running | completed | failed | superseded"),
			"trigger_type":         Str("manual | pipeline_completed"),
			"trigger_ref":          Str("Upstream work task or manual trigger reference"),
			"automation_id":        Str("Automation that requested the run"),
			"requested_at":         Str("Run request timestamp"),
			"started_at":           Str("Run start timestamp"),
			"completed_at":         Str("Run completion timestamp"),
			"rerun_requested":      Bool("Whether a follow-up coalesced rerun is required"),
			"superseded_by_run_id": Str("Follow-up run queued after coalescing"),
			"stage_states":         ObjMap("object"),
			"metrics":              M{"type": "object", "additionalProperties": true},
			"error":                Str("Failure summary, when status=failed"),
		}),
		"TwinProcessingRunCreateRequest": Props(nil, M{
			"trigger_type":  Str("manual | pipeline_completed"),
			"trigger_ref":   Str("Upstream trigger reference"),
			"automation_id": Str("Automation that requested the run"),
		}),
		"TwinSyncRun": Props(nil, M{
			"id":                             Str("Twin sync run ID (UUID)"),
			"digital_twin_id":                Str("Owning digital twin ID"),
			"trigger_type":                   Str("manual | pipeline_completed | webhook | scheduled | system"),
			"triggered_by":                   Str("Trigger actor or reference"),
			"source_ids":                     Arr(M{"type": "string"}),
			"ontology_version":               Str("Ontology version used during this sync run"),
			"reconciliation_strategy":        Str("source_priority | freshest"),
			"started_at":                     Str("ISO-8601 run start timestamp"),
			"completed_at":                   Str("ISO-8601 run completion timestamp"),
			"status":                         Str("running | completed | failed"),
			"summary":                        M{"type": "object", "additionalProperties": true},
			"entity_revision_high_watermark": Int("Highest entity revision seen when the run completed"),
			"base_snapshot_id":               Str("Optional snapshot anchor ID"),
			"error":                          Str("Failure reason when status=failed"),
			"RelationshipRevision": Props(nil, M{
				"id":                Str("Relationship revision ID (UUID)"),
				"digital_twin_id":   Str("Owning digital twin ID"),
				"sync_run_id":       Str("Sync run that emitted this relationship change"),
				"source_entity_id":  Str("Source entity ID"),
				"target_entity_id":  Str("Target entity ID"),
				"relationship_type": Str("Relationship type"),
				"revision":          Int("Monotonic relationship revision number"),
				"change_type":       Str("added | updated | removed"),
				"delta_data":        M{"type": "object", "additionalProperties": true},
				"full_state":        M{"type": "object", "additionalProperties": true},
				"provenance":        M{"type": "object", "additionalProperties": true},
				"recorded_at":       Str("ISO-8601 timestamp when this relationship revision was recorded"),
				"ontology_version":  Str("Ontology version used when this edge was emitted"),
			}),
			"TwinSnapshot": Props(nil, M{
				"id":                                   Str("Twin snapshot ID (UUID)"),
				"digital_twin_id":                      Str("Owning digital twin ID"),
				"sync_run_id":                          Str("Sync run that produced this snapshot"),
				"snapshot_kind":                        Str("full | checkpoint | branch_base"),
				"created_at":                           Str("ISO-8601 snapshot timestamp"),
				"entity_revision_high_watermark":       Int("Highest entity revision represented in the snapshot"),
				"relationship_revision_high_watermark": Int("Highest relationship revision represented in the snapshot"),
				"metadata":                             M{"type": "object", "additionalProperties": true},
			}),
			"ReconstructedTwinState": Props(nil, M{
				"digital_twin_id": Str("Owning digital twin ID"),
				"sync_run_id":     Str("Sync run that anchors this reconstructed state"),
				"snapshot_id":     Str("Snapshot used for reconstruction"),
				"entities":        ArrOf("Entity"),
				"relationships":   ArrOf("EntityRelationship"),
				"metadata":        M{"type": "object", "additionalProperties": true},
			}),
		}),

		"AlertEvent": Props(nil, M{
			"id":                           Str("Alert event ID (UUID)"),
			"project_id":                   Str("Owning project ID"),
			"digital_twin_id":              Str("Owning digital twin ID"),
			"processing_run_id":            Str("Processing run that emitted the alert"),
			"source_insight_id":            Str("Optional source insight ID"),
			"automation_id":                Str("Automation that emitted the alert"),
			"action_id":                    Str("Digital-twin action that matched"),
			"severity":                     Str("low | medium | high | critical"),
			"category":                     Str("Alert category"),
			"title":                        Str("Alert title"),
			"message":                      Str("Alert message"),
			"ontology_context":             M{"type": "object", "additionalProperties": true},
			"entity_refs":                  Arr(M{"type": "string"}),
			"requested_export_pipeline_id": Str("Export pipeline requested by the action"),
			"requested_trigger_params":     M{"type": "object", "additionalProperties": true},
			"approval_status":              Str("not_required | pending | approved | rejected"),
			"execution_status":             Str("pending_approval | queued | failed | rejected | skipped | not_applicable"),
			"execution_error":              Str("Pipeline queueing error when action execution failed"),
			"approval_requested_at":        Str("When manual approval was requested"),
			"approval_resolved_at":         Str("When manual approval was resolved"),
			"approval_actor":               Str("Operator or actor that resolved the approval"),
			"approval_note":                Str("Optional approval note"),
			"triggered_export_pipeline_id": Str("Export pipeline triggered by this alert, if any"),
			"triggered_work_task_id":       Str("Triggered export work task ID, if any"),
			"created_at":                   Str("Alert event timestamp"),
		}),
		"AlertApprovalRequest": Props([]string{"decision"}, M{
			"decision": Str("approve | reject"),
			"actor":    Str("Optional operator identity"),
			"note":     Str("Optional approval note"),
		}),

		"EntityRelationship": Props([]string{"type", "target_id", "target_type"}, M{
			"type":        Str("Relationship type from the ontology"),
			"target_id":   Str("Target entity ID"),
			"target_type": Str("Target entity type"),
			"properties":  M{"type": "object", "additionalProperties": true},
		}),
		"Entity": Props(nil, M{
			"id":              Str("Entity ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"type":            Str("Entity type from the ontology"),
			"attributes":      M{"type": "object", "additionalProperties": true},
			"source_data_id":  Str("Optional source CIR record ID"),
			"is_modified":     Bool("Whether the entity has in-memory modifications"),
			"modifications":   M{"type": "object", "additionalProperties": true},
			"relationships":   ArrOf("EntityRelationship"),
			"computed_values": M{"type": "object", "additionalProperties": true},
			"created_at":      Str("ISO-8601 creation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"EntityRevision": Props(nil, M{
			"id":              Str("Entity revision ID (UUID)"),
			"entity_id":       Str("Entity ID"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"revision":        Int("Monotonic revision number"),
			"attributes":      M{"type": "object", "additionalProperties": true},
			"modifications":   M{"type": "object", "additionalProperties": true},
			"computed_values": M{"type": "object", "additionalProperties": true},
			"relationships":   ArrOf("EntityRelationship"),
			"recorded_at":     Str("ISO-8601 timestamp when this revision was recorded"),
		}),
		"Prediction": Props(nil, M{
			"id":              Str("Prediction ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"model_id":        Str("Model ID"),
			"entity_id":       Str("Optional entity ID"),
			"entity_type":     Str("Optional entity type"),
			"prediction_type": Str("point | batch | anomaly"),
			"input":           M{"type": "object", "additionalProperties": true},
			"output":          M{"description": "Prediction output payload"},
			"confidence":      M{"type": "number", "description": "Prediction confidence [0,1]"},
			"cached_at":       Str("Prediction cache timestamp"),
			"expires_at":      Str("Prediction cache expiry timestamp"),
			"metadata":        M{"type": "object", "additionalProperties": true},
		}),
		"PredictionResult": M{
			"description": "Single prediction response or batch prediction array depending on request shape.",
			"oneOf":       S{Ref("Prediction"), ArrOf("Prediction")},
		},
		"ScenarioModification": Props([]string{"entity_type", "entity_id", "attribute", "original_value", "new_value"}, M{
			"entity_type":    Str("Entity type"),
			"entity_id":      Str("Entity ID"),
			"attribute":      Str("Attribute name"),
			"original_value": M{"description": "Original attribute value"},
			"new_value":      M{"description": "New attribute value"},
			"rationale":      Str("Optional explanation for the modification"),
		}),
		"ScenarioPrediction": Props([]string{"model_id", "model_name", "prediction"}, M{
			"model_id":    Str("Model ID"),
			"model_name":  Str("Model name"),
			"entity_id":   Str("Optional entity ID"),
			"entity_type": Str("Optional entity type"),
			"prediction":  M{"description": "Prediction payload"},
			"confidence":  M{"type": "number", "description": "Prediction confidence [0,1]"},
			"impact":      Str("Human-readable impact summary"),
			"metadata":    M{"type": "object", "additionalProperties": true},
		}),
		"Scenario": Props(nil, M{
			"id":              Str("Scenario ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"name":            Str("Scenario name"),
			"description":     Str("Description"),
			"base_state":      Str("current | historical"),
			"modifications":   ArrOf("ScenarioModification"),
			"predictions":     ArrOf("ScenarioPrediction"),
			"status":          Str("active | archived"),
			"created_by":      Str("Optional creator identity"),
			"created_at":      Str("ISO-8601 creation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ScenarioCreateRequest": Props([]string{"name", "modifications"}, M{
			"name":            Str("Scenario name"),
			"description":     Str("Description"),
			"base_state":      Str("current | historical"),
			"modifications":   ArrOf("ScenarioModification"),
			"run_predictions": Bool("Whether predictions should be generated immediately"),
		}),
		"ActionCondition": Props([]string{"operator", "threshold"}, M{
			"model_id":    Str("Optional model ID for prediction-based conditions"),
			"attribute":   Str("Optional entity attribute for attribute-based conditions"),
			"operator":    Str("gt | gte | lt | lte | eq | ne"),
			"threshold":   M{"description": "Comparison threshold value"},
			"entity_type": Str("Optional entity type filter"),
		}),
		"ActionTrigger": Props([]string{"pipeline_id"}, M{
			"pipeline_id":   Str("Pipeline ID to execute when the action fires"),
			"parameters":    M{"type": "object", "additionalProperties": true},
			"approval_mode": Str("automatic | manual"),
		}),
		"Action": Props(nil, M{
			"id":              Str("Action ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"name":            Str("Action name"),
			"description":     Str("Description"),
			"enabled":         Bool("Whether the action is active"),
			"condition":       Ref("ActionCondition"),
			"trigger":         Ref("ActionTrigger"),
			"last_triggered":  Str("ISO-8601 timestamp of the most recent trigger"),
			"trigger_count":   Int("Number of times the action has fired"),
			"created_at":      Str("ISO-8601 creation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ActionCreateRequest": Props([]string{"name", "condition", "trigger"}, M{
			"name":        Str("Action name"),
			"description": Str("Description"),
			"enabled":     Bool("Whether the action starts enabled"),
			"condition":   Ref("ActionCondition"),
			"trigger":     Ref("ActionTrigger"),
		}),
	}
}
