package doc

func storageAnalysisOntologyExtractionSchemas() M {
	return M{
		// ── Storage ──────────────────────────────────────────────────────────
		"StorageConfig": Props(nil, M{
			"id":          Str("Storage config ID (UUID)"),
			"project_id":  Str("Owning project ID"),
			"plugin_type": Str("filesystem | postgresql | mysql | mongodb | s3 | redis | elasticsearch | neo4j | <custom>"),
			"config":      M{"type": "object", "additionalProperties": true},
			"ontology_id": Str("Optional linked ontology ID"),
			"active":      Bool("Whether this config is active"),
			"created_at":  Str("ISO-8601 creation timestamp"),
			"updated_at":  Str("ISO-8601 last-updated timestamp"),
		}),
		"StorageConfigCreateRequest": Props([]string{"project_id", "plugin_type", "config"}, M{
			"project_id":  Str("Owning project ID"),
			"plugin_type": Str("Backend type"),
			"config":      M{"type": "object", "additionalProperties": true},
			"ontology_id": Str("Optional linked ontology ID"),
		}),
		"StorageConfigUpdateRequest": Props(nil, M{
			"config":      M{"type": "object", "additionalProperties": true},
			"ontology_id": Str("Linked ontology ID"),
			"active":      Bool("Active flag"),
		}),
		"CIR": M{
			"description": "Common Internal Representation — the normalised record format used across all storage backends.",
			"type":        "object",
			"properties": M{
				"id":       Str("CIR record ID"),
				"source":   M{"type": "object", "additionalProperties": true, "description": "Provenance information"},
				"data":     M{"type": "object", "additionalProperties": true, "description": "Record payload"},
				"metadata": M{"type": "object", "additionalProperties": true, "description": "Record metadata"},
			},
		},
		"CIRQuery": Props(nil, M{
			"entity_type": Str("Filter by entity type"),
			"filters":     ArrOf("CIRCondition"),
			"order_by":    ArrOf("OrderByClause"),
			"limit":       Int("Maximum results"),
			"offset":      Int("Pagination offset"),
		}),
		"CIRCondition": Props([]string{"attribute", "operator", "value"}, M{
			"attribute": Str("Attribute name"),
			"operator":  Str("eq | neq | gt | gte | lt | lte | in | like"),
			"value":     M{"description": "Filter value"},
		}),
		"OrderByClause": Props([]string{"attribute"}, M{
			"attribute": Str("Attribute to sort by"),
			"direction": Str("asc | desc (default asc)"),
		}),
		"StorageResult": Props(nil, M{
			"success":        Bool("Whether the operation succeeded"),
			"affected_items": Int("Number of records affected"),
			"error":          Str("Error message if unsuccessful"),
		}),
		"IngestionHealthSource": Props([]string{"storage_id", "plugin_type", "sample_size", "freshness_score", "completeness_score", "schema_drift_score", "overall_score", "status"}, M{
			"storage_id":         Str("Storage config ID"),
			"plugin_type":        Str("Storage backend plugin type"),
			"sample_size":        Int("Number of sampled CIR records"),
			"last_ingested_at":   Str("Latest ingestion timestamp in sample"),
			"freshness_score":    M{"type": "number", "description": "Freshness score [0,1]"},
			"completeness_score": M{"type": "number", "description": "Completeness score [0,1]"},
			"schema_drift_score": M{"type": "number", "description": "Schema stability score [0,1], higher is better"},
			"overall_score":      M{"type": "number", "description": "Weighted ingestion health score [0,1]"},
			"status":             Str("healthy | warning | critical"),
			"findings":           Arr(M{"type": "string"}),
		}),
		"IngestionHealthReport": Props([]string{"project_id", "generated_at", "overall_score", "status", "sources"}, M{
			"project_id":      Str("Project ID"),
			"generated_at":    Str("Report generation timestamp"),
			"overall_score":   M{"type": "number", "description": "Project-level ingestion health score [0,1]"},
			"status":          Str("healthy | warning | critical"),
			"sources":         ArrOf("IngestionHealthSource"),
			"recommendations": Arr(M{"type": "string"}),
		}),
		"StorageStoreRequest": Props([]string{"project_id", "storage_id", "cir_data"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"cir_data":   Ref("CIR"),
		}),
		"StorageQueryRequest": Props([]string{"project_id", "storage_id"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"query":      Ref("CIRQuery"),
		}),
		"StorageUpdateRequest": Props([]string{"project_id", "storage_id", "query", "updates"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"query":      Ref("CIRQuery"),
			"updates": Props(nil, M{
				"filters": ArrOf("CIRCondition"),
				"updates": M{"type": "object", "additionalProperties": true},
			}),
		}),
		"StorageDeleteRequest": Props([]string{"project_id", "storage_id", "query"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"query":      Ref("CIRQuery"),
		}),

		// ── Storage Plugins (dynamic) ─────────────────────────────────────────
		"ExternalStoragePlugin": Props(nil, M{
			"name":            Str("Plugin name derived from repository URL"),
			"version":         Str("Reserved for manifest-derived versions; empty when unavailable"),
			"description":     Str("Reserved for manifest-derived descriptions; empty when unavailable"),
			"author":          Str("Reserved for manifest-derived authors; empty when unavailable"),
			"repository_url":  Str("Git repository URL"),
			"git_commit_hash": Str("Commit SHA the current .so was compiled from"),
			"status":          Str("active | error"),
			"error_message":   Str("Compilation or load error, if status=error"),
			"installed_at":    Str("ISO-8601 installation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ExternalStoragePluginInstallRequest": Props([]string{"repository_url"}, M{
			"repository_url": Str("HTTPS or SSH Git URL of the storage plugin repository"),
			"git_ref":        Str("Branch, tag, or commit SHA (default: main)"),
		}),
		"ExternalLLMProvider": Props(nil, M{
			"name":            Str("Provider name derived from repository URL"),
			"repository_url":  Str("Git repository URL"),
			"git_commit_hash": Str("Commit SHA the current .so was compiled from"),
			"status":          Str("active | error"),
			"error_message":   Str("Compilation or load error, if status=error"),
			"installed_at":    Str("ISO-8601 installation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ExternalLLMProviderInstallRequest": Props([]string{"repository_url"}, M{
			"repository_url": Str("HTTPS or SSH Git URL of the LLM provider repository"),
			"git_ref":        Str("Branch, tag, or commit SHA (default: main)"),
		}),

		// ── Analysis ──────────────────────────────────────────────────────────
		"AnalysisRun": Props(nil, M{
			"id":                Str("Analysis run ID (UUID)"),
			"project_id":        Str("Owning project ID"),
			"kind":              Str("resolver | insights"),
			"status":            Str("completed | failed"),
			"source_ids":        Arr(M{"type": "string"}),
			"algorithm_version": Str("Detector/resolver algorithm version"),
			"policy_version":    Str("Resolver policy version string"),
			"coverage":          M{"type": "object", "additionalProperties": true},
			"metrics":           M{"type": "object", "additionalProperties": true},
			"error":             Str("Failure message, when status=failed"),
			"created_at":        Str("Run creation timestamp"),
			"completed_at":      Str("Run completion timestamp"),
		}),
		"ReviewDecisionEvent": Props([]string{"decision", "decided_at"}, M{
			"decision":        Str("accept | reject"),
			"reviewer":        Str("Reviewer identity, if provided"),
			"rationale":       Str("Optional rationale captured with the decision"),
			"previous_status": Str("Review item status before the decision was applied"),
			"decided_at":      Str("Decision timestamp"),
		}),
		"ReviewItem": Props(nil, M{
			"id":                 Str("Review item ID (UUID)"),
			"project_id":         Str("Owning project ID"),
			"run_id":             Str("Most recent analysis run ID"),
			"finding_type":       Str("cross_source_link or another finding category"),
			"finding_key":        Str("Stable finding identity used for upsert/reopen semantics"),
			"status":             Str("pending | accepted | rejected | auto_accepted"),
			"suggested_decision": Str("Suggested decision from the scoring policy"),
			"confidence":         M{"type": "number", "description": "Finding confidence [0,1]"},
			"occurrence_count":   Int("How many resolver runs have observed this finding"),
			"payload":            M{"type": "object", "additionalProperties": true},
			"evidence":           M{"type": "object", "additionalProperties": true},
			"rationale":          Str("Human-readable explanation"),
			"reviewer":           Str("Reviewer identity, if decided"),
			"reviewed_at":        Str("Decision timestamp"),
			"decision_history":   ArrOf("ReviewDecisionEvent"),
			"created_at":         Str("Creation timestamp"),
			"updated_at":         Str("Update timestamp"),
		}),
		"ReviewDecisionRequest": Props([]string{"decision"}, M{
			"decision":  Str("accept | reject"),
			"rationale": Str("Optional review rationale"),
			"reviewer":  Str("Optional reviewer identifier"),
		}),
		"Insight": Props(nil, M{
			"id":               Str("Insight ID (UUID)"),
			"project_id":       Str("Owning project ID"),
			"run_id":           Str("Analysis run that produced this insight"),
			"type":             Str("anomaly_spike | trend_break | cooccurrence_surge | other generic detector type"),
			"severity":         Str("low | medium | high | critical"),
			"confidence":       M{"type": "number", "description": "Insight confidence [0,1]"},
			"explanation":      Str("Human-readable rationale"),
			"suggested_action": Str("Suggested follow-up action"),
			"evidence":         M{"type": "object", "additionalProperties": true},
			"status":           Str("Insight lifecycle state"),
			"created_at":       Str("Creation timestamp"),
			"updated_at":       Str("Update timestamp"),
		}),
		"InsightGenerateRequest": Props([]string{"project_id"}, M{
			"project_id": Str("Project ID"),
		}),
		"ResolverRunRequest": Props([]string{"project_id", "storage_ids"}, M{
			"project_id":  Str("Project ID"),
			"storage_ids": Arr(M{"type": "string"}),
		}),

		// ── Ontologies ────────────────────────────────────────────────────────
		"Ontology": Props(nil, M{
			"id":           Str("Ontology ID (UUID)"),
			"project_id":   Str("Owning project ID"),
			"name":         Str("Ontology name"),
			"description":  Str("Ontology description"),
			"version":      Str("Version string"),
			"content":      Str("OWL/Turtle ontology content"),
			"status":       Str("draft | active | archived"),
			"is_generated": Bool("Whether the ontology was generated from extraction"),
			"created_at":   Str("ISO-8601 creation timestamp"),
			"updated_at":   Str("ISO-8601 last-updated timestamp"),
		}),
		"OntologyCreateRequest": Props([]string{"project_id", "name", "content"}, M{
			"project_id":  Str("Owning project ID"),
			"name":        Str("Ontology name"),
			"description": Str("Description"),
			"version":     Str("Version string"),
			"content":     Str("Initial OWL/Turtle content"),
			"status":      Str("draft | active | archived"),
		}),
		"OntologyUpdateRequest": Props(nil, M{
			"name":        Str("New name"),
			"description": Str("New description"),
			"version":     Str("New version string"),
			"content":     Str("Updated OWL/Turtle content"),
			"status":      Str("New status: draft | active | archived"),
		}),
		"OntologyDiagnostic": Props([]string{"severity", "code", "message"}, M{
			"severity": Str("error | warning | info"),
			"code":     Str("Stable diagnostic code"),
			"message":  Str("Human-readable diagnostic message"),
			"line":     Int("1-based source line when available"),
			"column":   Int("1-based source column when available"),
			"subject":  Str("Related ontology term or statement"),
		}),
		"CompiledOntologyClass": Props([]string{"id", "uri", "name"}, M{
			"id":           Str("Stable local class ID"),
			"uri":          Str("Expanded class URI"),
			"name":         Str("Local class name"),
			"label":        Str("Preferred label"),
			"description":  Str("Class description/comment"),
			"subclass_of":  Arr(M{"type": "string"}),
			"search_terms": Arr(M{"type": "string"}),
		}),
		"CompiledOntologyProperty": Props([]string{"id", "uri", "name", "kind"}, M{
			"id":           Str("Stable local property ID"),
			"uri":          Str("Expanded property URI"),
			"name":         Str("Local property name"),
			"label":        Str("Preferred label"),
			"description":  Str("Property description/comment"),
			"kind":         Str("datatype | object | annotation | unknown"),
			"domain":       Arr(M{"type": "string"}),
			"range":        Arr(M{"type": "string"}),
			"inverse_of":   Str("Inverse property ID"),
			"search_terms": Arr(M{"type": "string"}),
		}),
		"CompiledOntologyRelation": Props([]string{"property_id", "name", "from_class", "to_class", "uri"}, M{
			"property_id": Str("Object property ID"),
			"name":        Str("Relationship name"),
			"from_class":  Str("Domain class ID"),
			"to_class":    Str("Range class ID"),
			"uri":         Str("Expanded relationship URI"),
		}),
		"OntologySearchTerm": Props([]string{"term", "kind", "id", "uri", "weight"}, M{
			"term":        Str("Preferred searchable term"),
			"kind":        Str("class | property | relation"),
			"id":          Str("Matched term ID"),
			"uri":         Str("Expanded URI"),
			"weight":      M{"type": "number", "description": "Base semantic ranking weight"},
			"aliases":     Arr(M{"type": "string"}),
			"class_id":    Str("Related class ID"),
			"property_id": Str("Related property ID"),
		}),
		"OntologySearchResult": Props([]string{"term", "score", "match"}, M{
			"term":       Ref("OntologySearchTerm"),
			"score":      M{"type": "number", "description": "Ranked match score"},
			"match":      Str("Candidate label/alias that matched"),
			"diagnostic": Str("Optional retrieval diagnostic"),
		}),
		"CompiledOntology": Props([]string{"ontology_id", "project_id", "content_hash", "prefixes", "classes", "properties", "relations", "search_terms", "compiled_at"}, M{
			"ontology_id":  Str("Source ontology ID"),
			"project_id":   Str("Owning project ID"),
			"name":         Str("Ontology name"),
			"version":      Str("Ontology version"),
			"content_hash": Str("SHA-256 hash of raw Turtle content"),
			"prefixes":     ObjMap("string"),
			"classes":      ArrOf("CompiledOntologyClass"),
			"properties":   ArrOf("CompiledOntologyProperty"),
			"relations":    ArrOf("CompiledOntologyRelation"),
			"search_terms": ArrOf("OntologySearchTerm"),
			"diagnostics":  ArrOf("OntologyDiagnostic"),
			"compiled_at":  Str("ISO-8601 compilation timestamp"),
		}),
		"OntologyValidationRequest": Props([]string{"content"}, M{
			"project_id": Str("Optional owning project ID for context"),
			"name":       Str("Optional ontology name for context"),
			"version":    Str("Optional ontology version for context"),
			"content":    Str("OWL/Turtle content to validate"),
		}),
		"OntologyValidationResponse": Props([]string{"valid"}, M{
			"valid":       Bool("Whether the content compiled without error diagnostics"),
			"compiled":    Ref("CompiledOntology"),
			"diagnostics": ArrOf("OntologyDiagnostic"),
		}),
		"OntologyRetrieveFilter": Props([]string{"property", "operator", "value"}, M{
			"property": Str("Ontology property ID/name/label"),
			"operator": Str("eq | neq | gt | gte | lt | lte | contains"),
			"value":    M{"description": "Comparison value"},
		}),
		"OntologyRetrieveRequest": Props([]string{"project_id"}, M{
			"project_id":  Str("Owning project ID"),
			"class":       Str("Ontology class ID/name/label to retrieve"),
			"properties":  Arr(M{"type": "string"}),
			"filters":     ArrOf("OntologyRetrieveFilter"),
			"storage_ids": Arr(M{"type": "string"}),
			"limit":       Int("Maximum returned records"),
		}),
		"OntologyRetrieveResult": Props([]string{"storage_id", "class_id", "properties", "source"}, M{
			"storage_id": Str("Storage config that returned the CIR"),
			"class_id":   Str("Mapped ontology class"),
			"properties": M{"type": "object", "additionalProperties": true},
			"source":     Ref("CIRSource"),
			"violations": ArrOf("SemanticMappingViolation"),
		}),
		"OntologyRetrieveResponse": Props([]string{"ontology_id", "content_hash", "results", "count"}, M{
			"ontology_id":  Str("Ontology ID"),
			"content_hash": Str("Compiled ontology content hash"),
			"results":      ArrOf("OntologyRetrieveResult"),
			"count":        Int("Returned result count"),
		}),
		"OntologyAggregateMetric": Props([]string{"function"}, M{
			"property": Str("Ontology property to aggregate; optional for count"),
			"function": Str("count | sum | avg | min | max"),
		}),
		"OntologyAggregateRequest": Props([]string{"project_id", "metric"}, M{
			"project_id":  Str("Owning project ID"),
			"class":       Str("Ontology class ID/name/label to aggregate"),
			"metric":      Ref("OntologyAggregateMetric"),
			"group_by":    Arr(M{"type": "string"}),
			"filters":     ArrOf("OntologyRetrieveFilter"),
			"storage_ids": Arr(M{"type": "string"}),
			"limit":       Int("Maximum input records scanned"),
		}),
		"OntologyAggregateGroup": Props([]string{"key", "value", "count"}, M{
			"key":   M{"type": "object", "additionalProperties": true},
			"value": M{"type": "number", "description": "Aggregated metric value"},
			"count": Int("Number of records in the bucket"),
		}),
		"OntologyAggregateResponse": Props([]string{"ontology_id", "content_hash", "class_id", "function", "groups", "count"}, M{
			"ontology_id":  Str("Ontology ID"),
			"content_hash": Str("Compiled ontology content hash"),
			"class_id":     Str("Aggregated ontology class"),
			"property_id":  Str("Aggregated ontology property"),
			"function":     Str("Aggregation function"),
			"groups":       ArrOf("OntologyAggregateGroup"),
			"count":        Int("Group count"),
		}),

		"SemanticMappingViolation": Props([]string{"code", "message"}, M{
			"code":     Str("Stable violation code"),
			"message":  Str("Human-readable violation"),
			"field":    Str("Source field"),
			"expected": Str("Expected ontology range/type"),
			"actual":   Str("Observed value type"),
		}),
		"CIRSource": Props([]string{"type", "uri", "timestamp", "format"}, M{
			"type":       Str("api | file | database | stream"),
			"uri":        Str("Source identifier"),
			"timestamp":  Str("Ingestion timestamp"),
			"format":     Str("csv | json | xml | text | binary"),
			"parameters": M{"type": "object", "additionalProperties": true},
		}),
		// ── Extraction ────────────────────────────────────────────────────────
		"ExtractionRequest": Props([]string{"project_id", "storage_ids", "ontology_name"}, M{
			"project_id":           Str("Project ID"),
			"storage_ids":          Arr(M{"type": "string"}),
			"ontology_name":        Str("Name for the generated ontology"),
			"include_structured":   Bool("Whether to extract from structured data"),
			"include_unstructured": Bool("Whether to extract from unstructured data"),
		}),
		"ExtractionResult": Props(nil, M{
			"ontology":           Ref("Ontology"),
			"extraction_summary": M{"type": "object", "additionalProperties": true},
		}),

		"MLProviderModel": Props(nil, M{
			"name":         Str("Provider model identifier"),
			"display_name": Str("Human-readable model name"),
			"description":  Str("Description"),
			"capabilities": Arr(M{"type": "string"}),
		}),
		"MLProviderMetadata": Props(nil, M{
			"name":                Str("Provider name"),
			"display_name":        Str("Human-readable provider name"),
			"description":         Str("Description"),
			"models":              ArrOf("MLProviderModel"),
			"capabilities":        Arr(M{"type": "string"}),
			"supports_training":   Bool("Whether the provider can train models"),
			"supports_inference":  Bool("Whether the provider can run inference"),
			"supports_monitoring": Bool("Whether the provider supports monitoring hooks"),
		}),
	}
}
