package doc

func systemProjectPipelineSchemas() M {
	return M{
		// ── Metrics / System ───────────────────────────────────────────────────
		"SystemHealthResponse": Props([]string{"status", "ready", "queue_length", "failed_tasks"}, M{
			"status":          Str("healthy | degraded | unhealthy"),
			"ready":           Bool("Whether the orchestrator can currently serve requests"),
			"queue_length":    Int("Current queue depth"),
			"failed_tasks":    Int("Number of failed tasks currently tracked in memory"),
			"tasks_by_status": ObjMap("integer"),
			"tasks_by_type":   ObjMap("integer"),
		}),
		"ReadinessResponse": Props([]string{"status"}, M{
			"status": Str("ready | not ready"),
			"error":  Str("Readiness failure reason, when unavailable"),
		}),
		"MetricsResponse": Props(nil, M{
			"queue":           Props(nil, M{"length": Int("Current queue depth")}),
			"tasks_by_status": ObjMap("integer"),
			"tasks_by_type":   ObjMap("integer"),
			"timestamp":       Str("ISO-8601 UTC snapshot timestamp"),
		}),
		"FactoryResetResponse": Props([]string{"reset_at", "message"}, M{
			"reset_at": Str("ISO-8601 UTC timestamp when the reset completed"),
			"message":  Str("Human-readable summary of what the reset did and did not delete"),
		}),

		// ── Projects ─────────────────────────────────────────────────────────
		"ProjectMetadata": Props(nil, M{
			"created_at": Str("ISO-8601 creation timestamp"),
			"updated_at": Str("ISO-8601 last-updated timestamp"),
			"tags":       Arr(M{"type": "string"}),
		}),
		"ProjectSettings": Props(nil, M{
			"timezone":    Str("Project timezone identifier"),
			"environment": Str("Environment label such as development or production"),
		}),
		"Project": Props(nil, M{
			"id":          Str("Project ID (UUID)"),
			"name":        Str("Project name"),
			"description": Str("Project description"),
			"version":     Str("Project version"),
			"status":      Str("active | archived | draft"),
			"metadata":    Ref("ProjectMetadata"),
			"settings":    Ref("ProjectSettings"),
		}),
		"ProjectSectionState": Props(nil, M{
			"status": Str("inactive | in_progress | complete | error | attention"),
			"detail": Str("Human-readable state detail"),
			"count":  Int("Associated item count"),
			"pulse":  Bool("Whether the frontend should animate the indicator"),
		}),
		"ProjectStateSummary": Props([]string{"project_id", "generated_at", "sections"}, M{
			"project_id":   Str("Project ID"),
			"generated_at": Str("Snapshot timestamp"),
			"queue_length": Int("Current queue depth across all tasks"),
			"active_tasks": Int("Number of active tasks for the project"),
			"sections":     ObjMap("ProjectSectionState"),
		}),

		"ProjectCreateRequest": Props([]string{"name"}, M{
			"name":        Str("Project name"),
			"description": Str("Project description"),
			"version":     Str("Optional semantic version"),
			"status":      Str("Optional initial status"),
			"settings":    Ref("ProjectSettings"),
			"tags":        Arr(M{"type": "string"}),
		}),
		"ProjectUpdateRequest": Props(nil, M{
			"description": Str("New description"),
			"version":     Str("New semantic version"),
			"status":      Str("New status"),
			"settings":    Ref("ProjectSettings"),
			"tags":        Arr(M{"type": "string"}),
		}),
		"ProjectCloneRequest": Props([]string{"project_id", "name"}, M{
			"project_id": Str("ID of the project to clone"),
			"name":       Str("Name for the cloned project"),
		}),

		// ── Pipelines ────────────────────────────────────────────────────────
		"Pipeline": Props(nil, M{
			"id":             Str("Pipeline ID (UUID)"),
			"project_id":     Str("Owning project ID"),
			"name":           Str("Pipeline name"),
			"type":           Str("ingestion | processing | output"),
			"description":    Str("Pipeline description"),
			"steps":          ArrOf("PipelineStep"),
			"trigger_config": Ref("PipelineTriggerConfig"),
			"status":         Str("Pipeline status"),
			"created_at":     Str("ISO-8601 creation timestamp"),
			"updated_at":     Str("ISO-8601 last-updated timestamp"),
		}),
		"PipelineTriggerConfig": Props(nil, M{
			"allow_manual": Bool("Whether the pipeline can be triggered manually or system-side through the trigger endpoint"),
			"webhook":      Bool("Whether the pipeline accepts webhook-triggered execution"),
			"secret":       Str("Webhook secret used to authenticate remote trigger requests; redacted in pipeline responses"),
			"description":  Str("Optional operator-facing note about when this trigger should be used"),
		}),
		"PipelineStep": Props([]string{"name", "plugin", "action"}, M{
			"name":       Str("Step name (unique within pipeline)"),
			"plugin":     Str("Plugin name or 'default' for built-in actions"),
			"action":     Str("Action name within the plugin"),
			"parameters": M{"type": "object", "additionalProperties": true},
			"output":     ObjMap("string"),
		}),
		"PipelineCreateRequest": Props([]string{"project_id", "name", "type", "steps"}, M{
			"project_id":     Str("Owning project ID"),
			"name":           Str("Pipeline name"),
			"type":           Str("Pipeline type"),
			"description":    Str("Pipeline description"),
			"steps":          ArrOf("PipelineStep"),
			"trigger_config": Ref("PipelineTriggerConfig"),
		}),
		"PipelineUpdateRequest": Props(nil, M{
			"description":    Str("New description"),
			"steps":          ArrOf("PipelineStep"),
			"trigger_config": Ref("PipelineTriggerConfig"),
			"status":         Str("New status"),
		}),
		"PipelineCheckpoint": Props([]string{"project_id", "pipeline_id", "step_name", "version", "checkpoint"}, M{
			"project_id":  Str("Owning project ID"),
			"pipeline_id": Str("Pipeline ID"),
			"step_name":   Str("Pipeline step name"),
			"scope":       Str("Optional checkpoint scope"),
			"version":     Int("Optimistic lock version"),
			"checkpoint":  M{"type": "object", "additionalProperties": true},
			"created_at":  Str("ISO-8601 creation timestamp"),
			"updated_at":  Str("ISO-8601 last-updated timestamp"),
		}),
		"PipelineExecutionRequest": Props([]string{"pipeline_id"}, M{
			"pipeline_id":  Str("Pipeline ID to execute"),
			"trigger_type": Str("manual | scheduled | automatic"),
			"triggered_by": Str("Trigger source identifier"),
			"parameters":   M{"type": "object", "additionalProperties": true},
		}),
		"PipelineTriggerRequest": Props(nil, M{
			"trigger_type":    Str("manual | webhook | system"),
			"triggered_by":    Str("Who or what initiated this trigger"),
			"parameters":      M{"type": "object", "additionalProperties": true},
			"source_event_id": Str("Optional upstream event identifier for dedupe/audit"),
			"webhook_token":   Str("Optional webhook token when not supplied via header or query parameter"),
		}),

		// ── Schedules ─────────────────────────────────────────────────────────
		"Schedule": Props(nil, M{
			"id":            Str("Schedule ID (UUID)"),
			"project_id":    Str("Owning project ID"),
			"name":          Str("Schedule name"),
			"pipelines":     Arr(M{"type": "string"}),
			"cron_schedule": Str("Cron expression (e.g. '0 * * * *')"),
			"enabled":       Bool("Whether the schedule is active"),
			"created_at":    Str("ISO-8601 creation timestamp"),
			"updated_at":    Str("ISO-8601 last-updated timestamp"),
			"last_run":      Str("ISO-8601 timestamp of the last run"),
			"next_run":      Str("ISO-8601 timestamp of the next planned run"),
		}),
		"ScheduleCreateRequest": Props([]string{"project_id", "name", "pipelines", "cron_schedule"}, M{
			"project_id":    Str("Owning project ID"),
			"name":          Str("Schedule name"),
			"pipelines":     Arr(M{"type": "string"}),
			"cron_schedule": Str("Cron expression"),
			"enabled":       Bool("Start enabled (default true)"),
		}),
		"ScheduleUpdateRequest": Props(nil, M{
			"name":          Str("New name"),
			"pipelines":     Arr(M{"type": "string"}),
			"cron_schedule": Str("New cron expression"),
			"enabled":       Bool("Enable or disable"),
		}),
		"PluginArtifact": Props([]string{"id", "plugin_kind", "plugin_name", "digest", "status"}, M{
			"id":                Str("Artifact ID"),
			"plugin_kind":       Str("pipeline | ml_provider | storage | llm_provider"),
			"plugin_name":       Str("Plugin or provider name"),
			"source_repository": Str("Git repository URL"),
			"source_ref":        Str("Requested Git ref"),
			"source_commit":     Str("Resolved source commit"),
			"digest":            Str("SHA-256 artifact digest"),
			"size_bytes":        Int("Artifact size in bytes"),
			"go_version":        Str("Go version used to compile the artifact"),
			"goos":              Str("Target GOOS"),
			"goarch":            Str("Target GOARCH"),
			"host_version":      Str("Mimir host version used for build compatibility"),
			"symbol_name":       Str("Runtime symbol loaded from the artifact"),
			"status":            Str("building | active | error"),
			"error_message":     Str("Build/load error if status=error"),
			"created_at":        Str("ISO-8601 creation timestamp"),
			"updated_at":        Str("ISO-8601 update timestamp"),
		}),
		"Plugin": Props(nil, M{
			"id":                Str("Plugin ID"),
			"name":              Str("Manifest plugin name"),
			"version":           Str("Plugin version"),
			"description":       Str("Plugin description"),
			"author":            Str("Plugin author"),
			"repository_url":    Str("Git repository URL"),
			"git_commit_hash":   Str("Commit SHA validated at install/update time"),
			"plugin_definition": Ref("PluginDefinition"),
			"status":            Str("active | disabled | error"),
			"created_at":        Str("ISO-8601 creation timestamp"),
			"updated_at":        Str("ISO-8601 last-updated timestamp"),
			"last_loaded_at":    Str("ISO-8601 last worker/orchestrator load timestamp"),
			"actions":           ArrOf("PluginAction"),
			"artifacts":         ArrOf("PluginArtifact"),
		}),
		"PluginDefinition": Props([]string{"name", "version"}, M{
			"name":        Str("Manifest plugin name"),
			"version":     Str("Manifest version"),
			"description": Str("Description"),
			"author":      Str("Author"),
			"repository":  Str("Declared repository URL"),
			"domains":     Arr(M{"type": "string"}),
			"actions":     ArrOf("ActionSchema"),
			"ml_provider": Ref("MLProviderMetadata"),
		}),
		"ActionSchema": Props([]string{"name"}, M{
			"name":        Str("Action name used in pipeline steps"),
			"description": Str("Action description"),
			"parameters":  ArrOf("ParameterSchema"),
			"returns":     ArrOf("ReturnSchema"),
		}),
		"ParameterSchema": Props([]string{"name", "type"}, M{
			"name":        Str("Parameter name"),
			"type":        Str("Parameter type"),
			"required":    Bool("Whether the parameter is required"),
			"description": Str("Parameter description"),
		}),
		"ReturnSchema": Props([]string{"name", "type"}, M{
			"name":        Str("Return field name"),
			"type":        Str("Return field type"),
			"description": Str("Return field description"),
		}),
		"PluginAction": Props([]string{"id", "plugin_id", "name"}, M{
			"id":          Str("Action ID"),
			"plugin_id":   Str("Owning plugin ID"),
			"name":        Str("Action name used in pipeline steps"),
			"description": Str("Action description"),
			"parameters":  ArrOf("ParameterSchema"),
			"returns":     ArrOf("ReturnSchema"),
		}),
		"PluginInstallRequest": Props([]string{"repository_url"}, M{
			"repository_url": Str("HTTPS or SSH Git URL of the plugin repository"),
			"git_ref":        Str("Branch, tag, or commit SHA (default: main)"),
		}),
		"PluginUpdateRequest": Props(nil, M{
			"git_ref": Str("Branch, tag, or commit SHA to validate and update to"),
		}),
	}
}
