package doc

func init() {
	RegisterSchemas(M{
		// ── Metrics / System ───────────────────────────────────────────────────
		"SystemHealthResponse": Props([]string{"status", "ready", "queue_length", "failed_tasks"}, M{
			"status":          Str("healthy | degraded | unhealthy"),
			"ready":           Bool("Whether the orchestrator can currently serve requests"),
			"queue_length":    Int("Current queue depth"),
			"failed_tasks":    Int("Number of failed tasks currently tracked in memory"),
			"tasks_by_status": ObjMap("integer"),
			"tasks_by_type":   ObjMap("integer"),
		}),
		"ReadinessResponse": Props([]string{"status"}, M{
			"status": Str("ready | not ready"),
			"error":  Str("Readiness failure reason, when unavailable"),
		}),
		"MetricsResponse": Props(nil, M{
			"queue":           Props(nil, M{"length": Int("Current queue depth")}),
			"tasks_by_status": ObjMap("integer"),
			"tasks_by_type":   ObjMap("integer"),
			"timestamp":       Str("ISO-8601 UTC snapshot timestamp"),
		}),

		// ── Projects ─────────────────────────────────────────────────────────
		"ProjectMetadata": Props(nil, M{
			"created_at": Str("ISO-8601 creation timestamp"),
			"updated_at": Str("ISO-8601 last-updated timestamp"),
			"tags":       Arr(M{"type": "string"}),
		}),
		"ProjectComponents": Props(nil, M{
			"pipelines":       Arr(M{"type": "string"}),
			"ontologies":      Arr(M{"type": "string"}),
			"ml_models":       Arr(M{"type": "string"}),
			"digital_twins":   Arr(M{"type": "string"}),
			"storage_configs": Arr(M{"type": "string"}),
		}),
		"ProjectSettings": Props(nil, M{
			"timezone":        Str("Project timezone identifier"),
			"environment":     Str("Environment label such as development or production"),
			"onboarding_mode": Str("guided | advanced"),
		}),
		"Project": Props(nil, M{
			"id":          Str("Project ID (UUID)"),
			"name":        Str("Project name"),
			"description": Str("Project description"),
			"version":     Str("Project version"),
			"status":      Str("active | archived | draft"),
			"metadata":    Ref("ProjectMetadata"),
			"components":  Ref("ProjectComponents"),
			"settings":    Ref("ProjectSettings"),
		}),
		"ProjectSectionState": Props(nil, M{
			"status": Str("inactive | in_progress | complete | error | attention"),
			"detail": Str("Human-readable state detail"),
			"count":  Int("Associated item count"),
			"pulse":  Bool("Whether the frontend should animate the indicator"),
		}),
		"ProjectStateSummary": Props([]string{"project_id", "generated_at", "sections"}, M{
			"project_id":   Str("Project ID"),
			"generated_at": Str("Snapshot timestamp"),
			"queue_length": Int("Current queue depth across all tasks"),
			"active_tasks": Int("Number of active tasks for the project"),
			"sections":     ObjMap("ProjectSectionState"),
		}),

		"ProjectCreateRequest": Props([]string{"name"}, M{
			"name":        Str("Project name"),
			"description": Str("Project description"),
			"version":     Str("Optional semantic version"),
			"status":      Str("Optional initial status"),
			"components":  Ref("ProjectComponents"),
			"settings":    Ref("ProjectSettings"),
			"tags":        Arr(M{"type": "string"}),
		}),
		"ProjectUpdateRequest": Props(nil, M{
			"description": Str("New description"),
			"version":     Str("New semantic version"),
			"status":      Str("New status"),
			"settings":    Ref("ProjectSettings"),
			"tags":        Arr(M{"type": "string"}),
		}),
		"ProjectCloneRequest": Props([]string{"project_id", "name"}, M{
			"project_id": Str("ID of the project to clone"),
			"name":       Str("Name for the cloned project"),
		}),

		// ── Pipelines ────────────────────────────────────────────────────────
		"Pipeline": Props(nil, M{
			"id":             Str("Pipeline ID (UUID)"),
			"project_id":     Str("Owning project ID"),
			"name":           Str("Pipeline name"),
			"type":           Str("ingestion | processing | output"),
			"description":    Str("Pipeline description"),
			"steps":          ArrOf("PipelineStep"),
			"trigger_config": Ref("PipelineTriggerConfig"),
			"status":         Str("Pipeline status"),
			"created_at":     Str("ISO-8601 creation timestamp"),
			"updated_at":     Str("ISO-8601 last-updated timestamp"),
		}),
		"PipelineTriggerConfig": Props(nil, M{
			"allow_manual": Bool("Whether the pipeline can be triggered manually or system-side through the trigger endpoint"),
			"webhook":      Bool("Whether the pipeline accepts webhook-triggered execution"),
			"secret":       Str("Webhook secret used to authenticate remote trigger requests; redacted in pipeline responses"),
			"description":  Str("Optional operator-facing note about when this trigger should be used"),
		}),
		"PipelineStep": Props([]string{"name", "plugin", "action"}, M{
			"name":       Str("Step name (unique within pipeline)"),
			"plugin":     Str("Plugin name or 'default' for built-in actions"),
			"action":     Str("Action name within the plugin"),
			"parameters": M{"type": "object", "additionalProperties": true},
			"output":     ObjMap("string"),
		}),
		"PipelineCreateRequest": Props([]string{"project_id", "name", "type", "steps"}, M{
			"project_id":     Str("Owning project ID"),
			"name":           Str("Pipeline name"),
			"type":           Str("Pipeline type"),
			"description":    Str("Pipeline description"),
			"steps":          ArrOf("PipelineStep"),
			"trigger_config": Ref("PipelineTriggerConfig"),
		}),
		"PipelineUpdateRequest": Props(nil, M{
			"description":    Str("New description"),
			"steps":          ArrOf("PipelineStep"),
			"trigger_config": Ref("PipelineTriggerConfig"),
			"status":         Str("New status"),
		}),
		"PipelineCheckpoint": Props([]string{"project_id", "pipeline_id", "step_name", "version", "checkpoint"}, M{
			"project_id":  Str("Owning project ID"),
			"pipeline_id": Str("Pipeline ID"),
			"step_name":   Str("Pipeline step name"),
			"scope":       Str("Optional checkpoint scope"),
			"version":     Int("Optimistic lock version"),
			"checkpoint":  M{"type": "object", "additionalProperties": true},
			"created_at":  Str("ISO-8601 creation timestamp"),
			"updated_at":  Str("ISO-8601 last-updated timestamp"),
		}),
		"PipelineExecutionRequest": Props([]string{"pipeline_id"}, M{
			"pipeline_id":  Str("Pipeline ID to execute"),
			"trigger_type": Str("manual | scheduled | automatic"),
			"triggered_by": Str("Trigger source identifier"),
			"parameters":   M{"type": "object", "additionalProperties": true},
		}),
		"PipelineTriggerRequest": Props(nil, M{
			"trigger_type":    Str("manual | webhook | system"),
			"triggered_by":    Str("Who or what initiated this trigger"),
			"parameters":      M{"type": "object", "additionalProperties": true},
			"source_event_id": Str("Optional upstream event identifier for dedupe/audit"),
			"webhook_token":   Str("Optional webhook token when not supplied via header or query parameter"),
		}),

		// ── Schedules ─────────────────────────────────────────────────────────
		"Schedule": Props(nil, M{
			"id":            Str("Schedule ID (UUID)"),
			"project_id":    Str("Owning project ID"),
			"name":          Str("Schedule name"),
			"pipelines":     Arr(M{"type": "string"}),
			"cron_schedule": Str("Cron expression (e.g. '0 * * * *')"),
			"enabled":       Bool("Whether the schedule is active"),
			"created_at":    Str("ISO-8601 creation timestamp"),
			"updated_at":    Str("ISO-8601 last-updated timestamp"),
			"last_run":      Str("ISO-8601 timestamp of the last run"),
			"next_run":      Str("ISO-8601 timestamp of the next planned run"),
		}),
		"ScheduleCreateRequest": Props([]string{"project_id", "name", "pipelines", "cron_schedule"}, M{
			"project_id":    Str("Owning project ID"),
			"name":          Str("Schedule name"),
			"pipelines":     Arr(M{"type": "string"}),
			"cron_schedule": Str("Cron expression"),
			"enabled":       Bool("Start enabled (default true)"),
		}),
		"ScheduleUpdateRequest": Props(nil, M{
			"name":          Str("New name"),
			"pipelines":     Arr(M{"type": "string"}),
			"cron_schedule": Str("New cron expression"),
			"enabled":       Bool("Enable or disable"),
		}),

		// ── Connectors ────────────────────────────────────────────────────────
		"ConnectorFieldOption": Props([]string{"value", "label"}, M{
			"value": Str("Option value"),
			"label": Str("Display label"),
		}),
		"ConnectorField": Props([]string{"name", "label", "type", "required"}, M{
			"name":        Str("Field key"),
			"label":       Str("Human-readable field label"),
			"type":        Str("text | number | boolean | select"),
			"description": Str("Field description"),
			"required":    Bool("Whether the field is required"),
			"default":     M{"description": "Optional default value"},
			"options":     ArrOf("ConnectorFieldOption"),
		}),
		"ConnectorTemplate": Props([]string{"kind", "label", "description", "category", "pipeline_type", "supports_schedule", "fields"}, M{
			"kind":              Str("Template identifier"),
			"label":             Str("Display name"),
			"description":       Str("What this connector does"),
			"category":          Str("database | http | feed | file"),
			"pipeline_type":     Str("Pipeline type created by this connector"),
			"supports_schedule": Bool("Whether recurring execution is supported"),
			"fields":            ArrOf("ConnectorField"),
		}),
		"ConnectorScheduleRequest": Props([]string{"cron_schedule"}, M{
			"name":          Str("Optional schedule name override"),
			"cron_schedule": Str("Cron expression for recurring runs"),
			"enabled":       Bool("Whether the schedule starts enabled"),
		}),
		"ConnectorSetupRequest": Props([]string{"project_id", "kind", "name", "storage_id", "source_config"}, M{
			"project_id":    Str("Owning project ID"),
			"kind":          Str("Connector template kind"),
			"name":          Str("Pipeline name to create"),
			"description":   Str("Optional pipeline description"),
			"storage_id":    Str("Destination storage configuration ID"),
			"source_config": M{"type": "object", "additionalProperties": true},
			"schedule":      Ref("ConnectorScheduleRequest"),
		}),
		"ConnectorSetupResponse": Props([]string{"template", "pipeline"}, M{
			"template": Ref("ConnectorTemplate"),
			"pipeline": Ref("Pipeline"),
			"schedule": Ref("Schedule"),
		}),

		// ── Pipeline Plugins ─────────────────────────────────────────────────
		"Plugin": Props(nil, M{
			"name":           Str("Plugin name"),
			"version":        Str("Plugin version"),
			"description":    Str("Plugin description"),
			"author":         Str("Plugin author"),
			"repository_url": Str("Git repository URL"),
			"actions":        Arr(M{"type": "string"}),
			"installed_at":   Str("ISO-8601 installation timestamp"),
		}),
		"PluginInstallRequest": Props([]string{"repository_url"}, M{
			"repository_url": Str("HTTPS Git URL of the plugin repository"),
			"git_ref":        Str("Branch, tag, or commit SHA (default: main)"),
		}),
		"PluginUpdateRequest": Props(nil, M{
			"git_ref": Str("Branch, tag, or commit SHA to update to"),
		}),

		// ── Storage ──────────────────────────────────────────────────────────
		"StorageConfig": Props(nil, M{
			"id":          Str("Storage config ID (UUID)"),
			"project_id":  Str("Owning project ID"),
			"plugin_type": Str("filesystem | postgresql | mysql | mongodb | s3 | redis | elasticsearch | neo4j | <custom>"),
			"config":      M{"type": "object", "additionalProperties": true},
			"ontology_id": Str("Optional linked ontology ID"),
			"active":      Bool("Whether this config is active"),
			"created_at":  Str("ISO-8601 creation timestamp"),
			"updated_at":  Str("ISO-8601 last-updated timestamp"),
		}),
		"StorageConfigCreateRequest": Props([]string{"project_id", "plugin_type", "config"}, M{
			"project_id":  Str("Owning project ID"),
			"plugin_type": Str("Backend type"),
			"config":      M{"type": "object", "additionalProperties": true},
			"ontology_id": Str("Optional linked ontology ID"),
		}),
		"StorageConfigUpdateRequest": Props(nil, M{
			"config":      M{"type": "object", "additionalProperties": true},
			"ontology_id": Str("Linked ontology ID"),
			"active":      Bool("Active flag"),
		}),
		"CIR": M{
			"description": "Common Internal Representation — the normalised record format used across all storage backends.",
			"type":        "object",
			"properties": M{
				"id":       Str("CIR record ID"),
				"source":   M{"type": "object", "additionalProperties": true, "description": "Provenance information"},
				"data":     M{"type": "object", "additionalProperties": true, "description": "Record payload"},
				"metadata": M{"type": "object", "additionalProperties": true, "description": "Record metadata"},
			},
		},
		"CIRQuery": Props(nil, M{
			"entity_type": Str("Filter by entity type"),
			"filters":     ArrOf("CIRCondition"),
			"order_by":    ArrOf("OrderByClause"),
			"limit":       Int("Maximum results"),
			"offset":      Int("Pagination offset"),
		}),
		"CIRCondition": Props([]string{"attribute", "operator", "value"}, M{
			"attribute": Str("Attribute name"),
			"operator":  Str("eq | neq | gt | gte | lt | lte | in | like"),
			"value":     M{"description": "Filter value"},
		}),
		"OrderByClause": Props([]string{"attribute"}, M{
			"attribute": Str("Attribute to sort by"),
			"direction": Str("asc | desc (default asc)"),
		}),
		"StorageResult": Props(nil, M{
			"success":        Bool("Whether the operation succeeded"),
			"affected_items": Int("Number of records affected"),
			"error":          Str("Error message if unsuccessful"),
		}),
		"IngestionHealthSource": Props([]string{"storage_id", "plugin_type", "sample_size", "freshness_score", "completeness_score", "schema_drift_score", "overall_score", "status"}, M{
			"storage_id":         Str("Storage config ID"),
			"plugin_type":        Str("Storage backend plugin type"),
			"sample_size":        Int("Number of sampled CIR records"),
			"last_ingested_at":   Str("Latest ingestion timestamp in sample"),
			"freshness_score":    M{"type": "number", "description": "Freshness score [0,1]"},
			"completeness_score": M{"type": "number", "description": "Completeness score [0,1]"},
			"schema_drift_score": M{"type": "number", "description": "Schema stability score [0,1], higher is better"},
			"overall_score":      M{"type": "number", "description": "Weighted ingestion health score [0,1]"},
			"status":             Str("healthy | warning | critical"),
			"findings":           Arr(M{"type": "string"}),
		}),
		"IngestionHealthReport": Props([]string{"project_id", "generated_at", "overall_score", "status", "sources"}, M{
			"project_id":      Str("Project ID"),
			"generated_at":    Str("Report generation timestamp"),
			"overall_score":   M{"type": "number", "description": "Project-level ingestion health score [0,1]"},
			"status":          Str("healthy | warning | critical"),
			"sources":         ArrOf("IngestionHealthSource"),
			"recommendations": Arr(M{"type": "string"}),
		}),
		"StorageStoreRequest": Props([]string{"project_id", "storage_id", "cir_data"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"cir_data":   Ref("CIR"),
		}),
		"StorageQueryRequest": Props([]string{"project_id", "storage_id"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"query":      Ref("CIRQuery"),
		}),
		"StorageUpdateRequest": Props([]string{"project_id", "storage_id", "query", "updates"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"query":      Ref("CIRQuery"),
			"updates": Props(nil, M{
				"filters": ArrOf("CIRCondition"),
				"updates": M{"type": "object", "additionalProperties": true},
			}),
		}),
		"StorageDeleteRequest": Props([]string{"project_id", "storage_id", "query"}, M{
			"project_id": Str("Project ID"),
			"storage_id": Str("Storage config ID"),
			"query":      Ref("CIRQuery"),
		}),

		// ── Storage Plugins (dynamic) ─────────────────────────────────────────
		"ExternalStoragePlugin": Props(nil, M{
			"name":            Str("Plugin name (derived from repository URL)"),
			"version":         Str("Version from plugin.yaml"),
			"description":     Str("Description from plugin.yaml"),
			"author":          Str("Author from plugin.yaml"),
			"repository_url":  Str("Git repository URL"),
			"git_commit_hash": Str("Commit SHA the current .so was compiled from"),
			"status":          Str("active | error"),
			"error_message":   Str("Compilation or load error, if status=error"),
			"installed_at":    Str("ISO-8601 installation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ExternalStoragePluginInstallRequest": Props([]string{"repository_url"}, M{
			"repository_url": Str("HTTPS Git URL of the storage plugin repository"),
			"git_ref":        Str("Branch, tag, or commit SHA (default: main)"),
		}),

		// ── Analysis ──────────────────────────────────────────────────────────
		"AnalysisRun": Props(nil, M{
			"id":                Str("Analysis run ID (UUID)"),
			"project_id":        Str("Owning project ID"),
			"kind":              Str("resolver | insights"),
			"status":            Str("completed | failed"),
			"source_ids":        Arr(M{"type": "string"}),
			"algorithm_version": Str("Detector/resolver algorithm version"),
			"policy_version":    Str("Resolver policy version string"),
			"coverage":          M{"type": "object", "additionalProperties": true},
			"metrics":           M{"type": "object", "additionalProperties": true},
			"error":             Str("Failure message, when status=failed"),
			"created_at":        Str("Run creation timestamp"),
			"completed_at":      Str("Run completion timestamp"),
		}),
		"ReviewDecisionEvent": Props([]string{"decision", "decided_at"}, M{
			"decision":        Str("accept | reject"),
			"reviewer":        Str("Reviewer identity, if provided"),
			"rationale":       Str("Optional rationale captured with the decision"),
			"previous_status": Str("Review item status before the decision was applied"),
			"decided_at":      Str("Decision timestamp"),
		}),
		"ReviewItem": Props(nil, M{
			"id":                 Str("Review item ID (UUID)"),
			"project_id":         Str("Owning project ID"),
			"run_id":             Str("Most recent analysis run ID"),
			"finding_type":       Str("cross_source_link or another finding category"),
			"finding_key":        Str("Stable finding identity used for upsert/reopen semantics"),
			"status":             Str("pending | accepted | rejected | auto_accepted"),
			"suggested_decision": Str("Suggested decision from the scoring policy"),
			"confidence":         M{"type": "number", "description": "Finding confidence [0,1]"},
			"occurrence_count":   Int("How many resolver runs have observed this finding"),
			"payload":            M{"type": "object", "additionalProperties": true},
			"evidence":           M{"type": "object", "additionalProperties": true},
			"rationale":          Str("Human-readable explanation"),
			"reviewer":           Str("Reviewer identity, if decided"),
			"reviewed_at":        Str("Decision timestamp"),
			"decision_history":   ArrOf("ReviewDecisionEvent"),
			"created_at":         Str("Creation timestamp"),
			"updated_at":         Str("Update timestamp"),
		}),
		"ReviewDecisionRequest": Props([]string{"decision"}, M{
			"decision":  Str("accept | reject"),
			"rationale": Str("Optional review rationale"),
			"reviewer":  Str("Optional reviewer identifier"),
		}),
		"Insight": Props(nil, M{
			"id":               Str("Insight ID (UUID)"),
			"project_id":       Str("Owning project ID"),
			"run_id":           Str("Analysis run that produced this insight"),
			"type":             Str("anomaly_spike | trend_break | cooccurrence_surge | other generic detector type"),
			"severity":         Str("low | medium | high | critical"),
			"confidence":       M{"type": "number", "description": "Insight confidence [0,1]"},
			"explanation":      Str("Human-readable rationale"),
			"suggested_action": Str("Suggested follow-up action"),
			"evidence":         M{"type": "object", "additionalProperties": true},
			"status":           Str("Insight lifecycle state"),
			"created_at":       Str("Creation timestamp"),
			"updated_at":       Str("Update timestamp"),
		}),
		"InsightGenerateRequest": Props([]string{"project_id"}, M{
			"project_id": Str("Project ID"),
		}),
		"ResolverRunRequest": Props([]string{"project_id", "storage_ids"}, M{
			"project_id":  Str("Project ID"),
			"storage_ids": Arr(M{"type": "string"}),
		}),

		// ── Ontologies ────────────────────────────────────────────────────────
		"Ontology": Props(nil, M{
			"id":          Str("Ontology ID (UUID)"),
			"project_id":  Str("Owning project ID"),
			"name":        Str("Ontology name"),
			"description": Str("Ontology description"),
			"content":     Str("OWL/Turtle ontology content"),
			"status":      Str("draft | active | needs_review | deprecated"),
			"created_at":  Str("ISO-8601 creation timestamp"),
			"updated_at":  Str("ISO-8601 last-updated timestamp"),
		}),
		"OntologyCreateRequest": Props([]string{"project_id", "name"}, M{
			"project_id":  Str("Owning project ID"),
			"name":        Str("Ontology name"),
			"description": Str("Description"),
			"content":     Str("Initial OWL/Turtle content"),
		}),
		"OntologyUpdateRequest": Props(nil, M{
			"name":        Str("New name"),
			"description": Str("New description"),
			"content":     Str("Updated OWL/Turtle content"),
			"status":      Str("New status"),
		}),

		// ── Extraction ────────────────────────────────────────────────────────
		"ExtractionRequest": Props([]string{"project_id", "storage_id"}, M{
			"project_id":  Str("Project ID"),
			"storage_id":  Str("Storage config ID to extract from"),
			"ontology_id": Str("Existing ontology to diff against (optional)"),
		}),
		"ExtractionResult": Props(nil, M{
			"ontology":     Ref("Ontology"),
			"diff":         Obj("OntologyDiff — added/removed/modified classes and properties"),
			"needs_review": Bool("True if the diff is significant enough to flag for human review"),
		}),

		// ── ML Models ─────────────────────────────────────────────────────────
		"MLModel": Props(nil, M{
			"id":                   Str("ML model ID (UUID)"),
			"project_id":           Str("Owning project ID"),
			"ontology_id":          Str("Linked ontology ID"),
			"name":                 Str("Model name"),
			"description":          Str("Model description"),
			"type":                 Str("decision_tree | random_forest | regression | neural_network"),
			"status":               Str("draft | training | trained | failed | degraded | deprecated | archived"),
			"version":              Str("Model version string"),
			"is_recommended":       Bool("True if recommended by the recommendation engine"),
			"recommendation_score": Int("Recommendation engine score"),
			"training_config":      Obj("Training configuration"),
			"training_metrics":     Obj("Metrics recorded during training"),
			"training_task_id":     Str("Canonical async work-task handle while training is in progress"),
			"model_artifact_path":  Str("Orchestrator-local path to the persisted model artifact"),
			"performance_metrics":  Obj("Latest performance metrics"),
			"metadata":             M{"type": "object", "additionalProperties": true},
			"created_at":           Str("ISO-8601 creation timestamp"),
			"updated_at":           Str("ISO-8601 last-updated timestamp"),
		}),
		"MLModelCreateRequest": Props([]string{"project_id", "name", "type"}, M{
			"project_id":      Str("Owning project ID"),
			"ontology_id":     Str("Linked ontology ID"),
			"name":            Str("Model name"),
			"description":     Str("Description"),
			"type":            Str("Model type"),
			"training_config": Obj("Training configuration"),
		}),
		"MLModelUpdateRequest": Props(nil, M{
			"name":                Str("New name"),
			"description":         Str("New description"),
			"training_config":     Obj("Updated training configuration"),
			"training_metrics":    Obj("Updated training metrics"),
			"performance_metrics": Obj("Updated performance metrics"),
			"status":              Str("New status"),
			"metadata":            M{"type": "object", "additionalProperties": true},
		}),
		"ModelRecommendationRequest": Props([]string{"project_id"}, M{
			"project_id":  Str("Project ID"),
			"ontology_id": Str("Ontology to base recommendation on"),
		}),
		"ModelRecommendation": Props(nil, M{
			"recommended_type": Str("Recommended model type"),
			"score":            Int("Confidence score (0-100)"),
			"reason":           Str("Explanation"),
			"alternatives":     Arr(Obj("Alternative model type with score and reason")),
		}),
		"ModelTrainingRequest": Props([]string{"model_id"}, M{
			"model_id":        Str("ID of the model to train"),
			"storage_ids":     Arr(M{"type": "string"}),
			"training_config": Obj("Optional training configuration override"),
		}),
		"TrainingCompleteRequest": Props([]string{"artifact_data_base64", "performance_metrics"}, M{
			"artifact_data_base64": Str("Base64-encoded serialized model artifact uploaded by the worker"),
			"performance_metrics":  Obj("Final performance metrics for the trained model"),
		}),
		"TrainingFailRequest": Props([]string{"reason"}, M{
			"reason": Str("Training failure reason recorded by the worker"),
		}),

		// ── Digital Twins ─────────────────────────────────────────────────────
		"DigitalTwinConfig": Props(nil, M{
			"storage_ids":          Arr(M{"type": "string"}),
			"enable_predictions":   Bool("Whether prediction endpoints are enabled for this twin"),
			"prediction_cache_ttl": Int("Prediction cache TTL in seconds"),
			"custom_settings":      M{"type": "object", "additionalProperties": M{"type": "string"}},
		}),
		"DigitalTwin": Props(nil, M{
			"id":           Str("Digital twin ID (UUID)"),
			"project_id":   Str("Owning project ID"),
			"ontology_id":  Str("Linked ontology ID"),
			"name":         Str("Digital twin name"),
			"description":  Str("Description"),
			"status":       Str("active | syncing | error"),
			"config":       Ref("DigitalTwinConfig"),
			"metadata":     M{"type": "object", "additionalProperties": true},
			"created_at":   Str("ISO-8601 creation timestamp"),
			"updated_at":   Str("ISO-8601 last-updated timestamp"),
			"last_sync_at": Str("ISO-8601 timestamp of the most recent completed sync"),
		}),
		"DigitalTwinCreateRequest": Props([]string{"project_id", "ontology_id", "name"}, M{
			"project_id":  Str("Owning project ID"),
			"ontology_id": Str("Linked ontology ID"),
			"name":        Str("Digital twin name"),
			"description": Str("Description"),
			"config":      Ref("DigitalTwinConfig"),
		}),
		"DigitalTwinUpdateRequest": Props(nil, M{
			"name":        Str("New name"),
			"description": Str("New description"),
			"status":      Str("New status"),
			"config":      Ref("DigitalTwinConfig"),
		}),
		"Automation": Props(nil, M{
			"id":               Str("Automation ID (UUID)"),
			"project_id":       Str("Owning project ID"),
			"name":             Str("Automation name"),
			"description":      Str("Description"),
			"enabled":          Bool("Whether the automation is active"),
			"target_type":      Str("pipeline | digital_twin"),
			"target_id":        Str("Target resource ID"),
			"trigger_type":     Str("pipeline_completed | manual"),
			"trigger_config":   M{"type": "object", "additionalProperties": true},
			"condition_config": M{"type": "object", "additionalProperties": true},
			"action_type":      Str("process_twin | trigger_export_pipeline"),
			"action_config":    M{"type": "object", "additionalProperties": true},
			"created_at":       Str("ISO-8601 creation timestamp"),
			"updated_at":       Str("ISO-8601 last-updated timestamp"),
		}),
		"AutomationCreateRequest": Props([]string{"name"}, M{
			"name":             Str("Automation name"),
			"description":      Str("Description"),
			"enabled":          Bool("Whether the automation starts enabled"),
			"target_type":      Str("pipeline | digital_twin (overridden for twin-scoped routes)"),
			"target_id":        Str("Target resource ID (overridden for twin-scoped routes)"),
			"trigger_type":     Str("pipeline_completed | manual"),
			"trigger_config":   M{"type": "object", "additionalProperties": true},
			"condition_config": M{"type": "object", "additionalProperties": true},
			"action_type":      Str("process_twin | trigger_export_pipeline"),
			"action_config":    M{"type": "object", "additionalProperties": true},
		}),
		"AutomationUpdateRequest": Props(nil, M{
			"name":             Str("Automation name"),
			"description":      Str("Description"),
			"enabled":          Bool("Whether the automation is active"),
			"trigger_type":     Str("pipeline_completed | manual"),
			"trigger_config":   M{"type": "object", "additionalProperties": true},
			"condition_config": M{"type": "object", "additionalProperties": true},
			"action_type":      Str("process_twin | trigger_export_pipeline"),
			"action_config":    M{"type": "object", "additionalProperties": true},
		}),
		"TwinProcessingStageState": Props(nil, M{
			"status":       Str("queued | running | completed | failed | skipped"),
			"started_at":   Str("Stage start timestamp"),
			"completed_at": Str("Stage completion timestamp"),
			"metrics":      M{"type": "object", "additionalProperties": true},
			"error":        Str("Stage error, if any"),
		}),
		"TwinProcessingRun": Props(nil, M{
			"id":                   Str("Twin processing run ID (UUID)"),
			"project_id":           Str("Owning project ID"),
			"digital_twin_id":      Str("Owning digital twin ID"),
			"status":               Str("queued | running | completed | failed | superseded"),
			"trigger_type":         Str("manual | pipeline_completed"),
			"trigger_ref":          Str("Upstream work task or manual trigger reference"),
			"automation_id":        Str("Automation that requested the run"),
			"requested_at":         Str("Run request timestamp"),
			"started_at":           Str("Run start timestamp"),
			"completed_at":         Str("Run completion timestamp"),
			"rerun_requested":      Bool("Whether a follow-up coalesced rerun is required"),
			"superseded_by_run_id": Str("Follow-up run queued after coalescing"),
			"stage_states":         ObjMap("object"),
			"metrics":              M{"type": "object", "additionalProperties": true},
			"error":                Str("Failure summary, when status=failed"),
		}),
		"TwinProcessingRunCreateRequest": Props(nil, M{
			"trigger_type":  Str("manual | pipeline_completed"),
			"trigger_ref":   Str("Upstream trigger reference"),
			"automation_id": Str("Automation that requested the run"),
		}),
		"AlertEvent": Props(nil, M{
			"id":                           Str("Alert event ID (UUID)"),
			"project_id":                   Str("Owning project ID"),
			"digital_twin_id":              Str("Owning digital twin ID"),
			"processing_run_id":            Str("Processing run that emitted the alert"),
			"source_insight_id":            Str("Optional source insight ID"),
			"automation_id":                Str("Automation that emitted the alert"),
			"action_id":                    Str("Digital-twin action that matched"),
			"severity":                     Str("low | medium | high | critical"),
			"category":                     Str("Alert category"),
			"title":                        Str("Alert title"),
			"message":                      Str("Alert message"),
			"ontology_context":             M{"type": "object", "additionalProperties": true},
			"entity_refs":                  Arr(M{"type": "string"}),
			"requested_export_pipeline_id": Str("Export pipeline requested by the action"),
			"requested_trigger_params":     M{"type": "object", "additionalProperties": true},
			"approval_status":              Str("not_required | pending | approved | rejected"),
			"approval_requested_at":        Str("When manual approval was requested"),
			"approval_resolved_at":         Str("When manual approval was resolved"),
			"approval_actor":               Str("Operator or actor that resolved the approval"),
			"approval_note":                Str("Optional approval note"),
			"triggered_export_pipeline_id": Str("Export pipeline triggered by this alert, if any"),
			"triggered_work_task_id":       Str("Triggered export work task ID, if any"),
			"created_at":                   Str("Alert event timestamp"),
		}),
		"AlertApprovalRequest": Props([]string{"decision"}, M{
			"decision": Str("approve | reject"),
			"actor":    Str("Optional operator identity"),
			"note":     Str("Optional approval note"),
		}),

		"EntityRelationship": Props([]string{"type", "target_id", "target_type"}, M{
			"type":        Str("Relationship type from the ontology"),
			"target_id":   Str("Target entity ID"),
			"target_type": Str("Target entity type"),
			"properties":  M{"type": "object", "additionalProperties": true},
		}),
		"Entity": Props(nil, M{
			"id":              Str("Entity ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"type":            Str("Entity type from the ontology"),
			"attributes":      M{"type": "object", "additionalProperties": true},
			"source_data_id":  Str("Optional source CIR record ID"),
			"is_modified":     Bool("Whether the entity has in-memory modifications"),
			"modifications":   M{"type": "object", "additionalProperties": true},
			"relationships":   ArrOf("EntityRelationship"),
			"computed_values": M{"type": "object", "additionalProperties": true},
			"created_at":      Str("ISO-8601 creation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"EntityRevision": Props(nil, M{
			"id":              Str("Entity revision ID (UUID)"),
			"entity_id":       Str("Entity ID"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"revision":        Int("Monotonic revision number"),
			"attributes":      M{"type": "object", "additionalProperties": true},
			"modifications":   M{"type": "object", "additionalProperties": true},
			"computed_values": M{"type": "object", "additionalProperties": true},
			"relationships":   ArrOf("EntityRelationship"),
			"recorded_at":     Str("ISO-8601 timestamp when this revision was recorded"),
		}),
		"Prediction": Props(nil, M{
			"id":              Str("Prediction ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"model_id":        Str("Model ID"),
			"entity_id":       Str("Optional entity ID"),
			"entity_type":     Str("Optional entity type"),
			"prediction_type": Str("point | batch | anomaly"),
			"input":           M{"type": "object", "additionalProperties": true},
			"output":          M{"description": "Prediction output payload"},
			"confidence":      M{"type": "number", "description": "Prediction confidence [0,1]"},
			"cached_at":       Str("Prediction cache timestamp"),
			"expires_at":      Str("Prediction cache expiry timestamp"),
			"metadata":        M{"type": "object", "additionalProperties": true},
		}),
		"PredictionResult": M{
			"description": "Single prediction response or batch prediction array depending on request shape.",
			"oneOf":       S{Ref("Prediction"), ArrOf("Prediction")},
		},
		"ScenarioModification": Props([]string{"entity_type", "entity_id", "attribute", "original_value", "new_value"}, M{
			"entity_type":    Str("Entity type"),
			"entity_id":      Str("Entity ID"),
			"attribute":      Str("Attribute name"),
			"original_value": M{"description": "Original attribute value"},
			"new_value":      M{"description": "New attribute value"},
			"rationale":      Str("Optional explanation for the modification"),
		}),
		"ScenarioPrediction": Props([]string{"model_id", "model_name", "prediction"}, M{
			"model_id":    Str("Model ID"),
			"model_name":  Str("Model name"),
			"entity_id":   Str("Optional entity ID"),
			"entity_type": Str("Optional entity type"),
			"prediction":  M{"description": "Prediction payload"},
			"confidence":  M{"type": "number", "description": "Prediction confidence [0,1]"},
			"impact":      Str("Human-readable impact summary"),
			"metadata":    M{"type": "object", "additionalProperties": true},
		}),
		"Scenario": Props(nil, M{
			"id":              Str("Scenario ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"name":            Str("Scenario name"),
			"description":     Str("Description"),
			"base_state":      Str("current | historical"),
			"modifications":   ArrOf("ScenarioModification"),
			"predictions":     ArrOf("ScenarioPrediction"),
			"status":          Str("active | archived"),
			"created_by":      Str("Optional creator identity"),
			"created_at":      Str("ISO-8601 creation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ScenarioCreateRequest": Props([]string{"name", "modifications"}, M{
			"name":            Str("Scenario name"),
			"description":     Str("Description"),
			"base_state":      Str("current | historical"),
			"modifications":   ArrOf("ScenarioModification"),
			"run_predictions": Bool("Whether predictions should be generated immediately"),
		}),
		"ActionCondition": Props([]string{"operator", "threshold"}, M{
			"model_id":    Str("Optional model ID for prediction-based conditions"),
			"attribute":   Str("Optional entity attribute for attribute-based conditions"),
			"operator":    Str("gt | gte | lt | lte | eq | ne"),
			"threshold":   M{"description": "Comparison threshold value"},
			"entity_type": Str("Optional entity type filter"),
		}),
		"ActionTrigger": Props([]string{"pipeline_id"}, M{
			"pipeline_id":   Str("Pipeline ID to execute when the action fires"),
			"parameters":    M{"type": "object", "additionalProperties": true},
			"approval_mode": Str("automatic | manual"),
		}),
		"Action": Props(nil, M{
			"id":              Str("Action ID (UUID)"),
			"digital_twin_id": Str("Owning digital twin ID"),
			"name":            Str("Action name"),
			"description":     Str("Description"),
			"enabled":         Bool("Whether the action is active"),
			"condition":       Ref("ActionCondition"),
			"trigger":         Ref("ActionTrigger"),
			"last_triggered":  Str("ISO-8601 timestamp of the most recent trigger"),
			"trigger_count":   Int("Number of times the action has fired"),
			"created_at":      Str("ISO-8601 creation timestamp"),
			"updated_at":      Str("ISO-8601 last-updated timestamp"),
		}),
		"ActionCreateRequest": Props([]string{"name", "condition", "trigger"}, M{
			"name":        Str("Action name"),
			"description": Str("Description"),
			"enabled":     Bool("Whether the action starts enabled"),
			"condition":   Ref("ActionCondition"),
			"trigger":     Ref("ActionTrigger"),
		}),

		// ── Work Tasks ────────────────────────────────────────────────────────
		"WorkTask": Props(nil, M{
			"id":                    Str("Work task ID (UUID)"),
			"type":                  Str("pipeline_execution | ml_training | ml_inference | digital_twin_processing"),
			"status":                Str("queued | scheduled | spawned | executing | completed | failed | timeout | cancelled"),
			"priority":              Int("Task priority (higher = processed first)"),
			"project_id":            Str("Owning project ID"),
			"submitted_at":          Str("ISO-8601 submission timestamp"),
			"started_at":            Str("ISO-8601 start timestamp"),
			"completed_at":          Str("ISO-8601 completion timestamp"),
			"output_location":       Str("Worker output location, if any"),
			"result_metadata":       M{"type": "object", "additionalProperties": true},
			"error_message":         Str("Error message if task failed"),
			"retry_count":           Int("Number of retries so far"),
			"max_retries":           Int("Maximum retry attempts"),
			"task_spec":             M{"type": "object", "additionalProperties": true},
			"resource_requirements": M{"type": "object", "additionalProperties": true},
		}),
		"WorkTaskSubmissionRequest": Props([]string{"type", "project_id"}, M{
			"type":                  Str("Task type"),
			"project_id":            Str("Owning project ID"),
			"priority":              Int("Task priority"),
			"task_spec":             M{"type": "object", "additionalProperties": true},
			"resource_requirements": M{"type": "object", "additionalProperties": true},
			"data_access":           M{"type": "object", "additionalProperties": true},
		}),
		"WorkTaskListResponse": Props([]string{"tasks", "queue_length"}, M{
			"tasks":        ArrOf("WorkTask"),
			"queue_length": Int("Number of currently queued tasks"),
		}),
		"WorkTaskResult": Props([]string{"status"}, M{
			"status":          Str("queued | scheduled | spawned | executing | completed | failed | timeout | cancelled"),
			"output_location": Str("Worker output location, if any"),
			"metadata":        M{"type": "object", "additionalProperties": true},
			"error_message":   Str("Error message if failed"),
		}),
	})
}
